### ISSUE TITLE
Not works shoot

### ISSUE THREAD

**Issue by alex2534alex** [onebone/MineCombat#10]
@onebone , help plz.
There is a trouble on shoot (Pistol/Gun):

> [06:53:43] [Asynchronous Worker #2 thread/CRITICAL]: RuntimeException: "Threaded members previously set to Threaded objects are immutable, cannot overwrite ret" (EXCEPTION) in "/MineCombat_v1.0/src/onebone/minecombat/task/ShootTask" at line 64
> [06:53:43] [Asynchronous Worker #2 thread/DEBUG]: #0 (): pocketmine\scheduler\AsyncTask->run(boolean)
> [06:53:43] [Server thread/CRITICAL]: Could not execute asynchronous task ShootTask: Task crashed

**Comment by alex2534alex** [comment]
Linux
PHP7, Genisys

**Comment by marcosvkp** [comment]
he is STAR

**Comment by onebone** [comment]
This project is no longer maintained.
