### ISSUE TITLE
Invaild Level Name

### ISSUE THREAD

**Issue by bonu1004** [onebone/MineCombat#2]
[MineCombat] Invaild level name was given 
이라며 서버가 자동으로 꺼지네요.

**Comment by HelloWorld017** [comment]
onebone님께 리포팅 부탁드립니다.

**Comment by HelloWorld017** [comment]
어 죄송합니다. 잘못봤네요

**Comment by onebone** [comment]
스폰 지점으로 지정하신 월드를 삭제하셨거나, 임의로 설정 파일을 수정하셔서 그런 것 같네요.
