### ISSUE TITLE
it is hard to shoot

### ISSUE THREAD

**Issue by ghost** [onebone/MineCombat#5]
please change the way to shoot, maybe tap on the air ? :)

**Comment by onebone** [comment]
I wish it was possible :(

**Comment by legoboy0215** [comment]
@onebone, Can you make a gun API?

**Comment by HelloWorld017** [comment]
There is a gun API. You can make it like https://github.com/HelloWorld017/CombatPlus

**Comment by Jackboy320** [comment]
These guns to download how i can use they?

**Comment by legoboy0215** [comment]
wow!!!
